// --- TECAdress.js ---
export const TECAdress = [
  {site_name: "1097 Enterprise", address: "600 Boll Weevil Circle", city: "Enterprise", state_province: "Iowa", zip: "52555"},
  {site_name: "120 Clanton", address: "1415 7Th Street South", city: "Clanton", state_province: "Iowa", zip: "52146"},
  {site_name: "135 Fort Payne", address: "2001 Glenn Bldv Sw", city: "Fort Payne", state_province: "Iowa", zip: "50042"},
  {site_name: "143 Haleyville", address: "42417 Hwy 195", city: "Haleyville", state_province: "Arkansas", zip: "72055"},
  {site_name: "1443 Huntsville", address: "6140A Univ Drive", city: "Huntsville", state_province: "Iowa", zip: "52345"},
  {site_name: "146 Bella Vista", address: "1750 Forest Hills Blvd", city: "Bella Vista", state_province: "Arkansas", zip: "72715"},
  {site_name: "1475 Montgomery", address: "851 Ann St", city: "Montgomery", state_province: "Missouri", zip: "63382"},
  {site_name: "152 Wilmot", address: "202 Mccombs St", city: "Wilmot", state_province: "Arkansas", zip: "71676"},
  {site_name: "156 Semmes", address: "7855 Moffett Rd", city: "Semmes", state_province: "Iowa", zip: "52318"},
  {site_name: "157 Sylacauga", address: "41301 US Hwy 280", city: "Sylacauga", state_province: "Iowa", zip: "50613"},
  {site_name: "158 Russellville", address: "13675 Hwy 43", city: "Russellville", state_province: "Arkansas", zip: "71663"},
  {site_name: "171 Scottsboro", address: "24833 Johnt Reidprkw", city: "Scottsboro", state_province: "Arkansas", zip: "72634"},
  {site_name: "1837 Winfield", address: "2575 Us Hwy 43", city: "Winfield", state_province: "Oklahoma", zip: "73739"},
  {site_name: "184 Talladega", address: "214 Haynes Street", city: "Talladega", state_province: "Iowa", zip: "50626"},
  {site_name: "187 Tallassee", address: "1300 Gilmer Ave", city: "Tallassee", state_province: "Minnesota", zip: "55787"},
  {site_name: "1871 Vestavia Hills", address: "1300 Montgomery Highway", city: "Vestavia Hills", state_province: "Oklahoma", zip: "74960"},
  {site_name: "200 Cedar Falls", address: "221 W 6Th St", city: "Cedar Falls", state_province: "Iowa", zip: "50613"},
  {site_name: "208 Dewar", address: "5916 1St St", city: "Dewar", state_province: "Iowa", zip: "50623"},
  {site_name: "222 Pilot Mound", address: "102 Pilot St", city: "Pilot Mound", state_province: "Iowa", zip: "50223"},
  {site_name: "226 Quasqueton", address: "113 E Dubuque St", city: "Quasqueton", state_province: "Iowa", zip: "52326"},
  {site_name: "227 Winthrop", address: "253 W Madison St", city: "Winthrop", state_province: "Iowa", zip: "50682"},
  {site_name: "228 Brandon", address: "704 Main St", city: "Brandon", state_province: "Iowa", zip: "52210"},
  {site_name: "229 Independence", address: "200 2Nd Ave Ne", city: "Independence", state_province: "Iowa", zip: "50644"},
  {site_name: "237 Rowley", address: "111 Ely St", city: "Rowley", state_province: "Iowa", zip: "52329"},
  {site_name: "24 Hazleton", address: "200 Main St S", city: "Hazleton", state_province: "Iowa", zip: "50641"},
  {site_name: "240 Marathon", address: "114 Agora St", city: "Marathon", state_province: "Iowa", zip: "50565"},
  {site_name: "250 Ayr", address: "4075 W Lincoln St", city: "Ayr", state_province: "Nebraska", zip: "68925"},
  {site_name: "251 Albert City", address: "114 Main St", city: "Albert City", state_province: "Iowa", zip: "50510"},
  {site_name: "254 Rembrandt", address: "107 E Main St", city: "Rembrandt", state_province: "Iowa", zip: "50576"},
  {site_name: "26 Aitkin", address: "15 Minnesota Ave N", city: "Aitkin", state_province: "Minnesota", zip: "56431"},
  {site_name: "2731 Alta", address: "106 S Cherokee St", city: "Alta", state_province: "Iowa", zip: "51002"},
  {site_name: "28 Sioux Rapids", address: "114 Thomas St", city: "Sioux Rapids", state_province: "Iowa", zip: "50585"},
  {site_name: "29 Washburn", address: "303 Main St", city: "Washburn", state_province: "Missouri", zip: "65772"},
  {site_name: "292 Aredale", address: "117 E Main St", city: "Aredale", state_province: "Iowa", zip: "50605"},
  {site_name: "302 Parkersburg", address: "602 Coates St", city: "Parkersburg", state_province: "Iowa", zip: "50665"},
  {site_name: "32 Shell Rock", address: "203 S Walnut St", city: "Shell Rock", state_province: "Iowa", zip: "50670"},
  {site_name: "320 Northglenn", address: "850 W 112Th Ave", city: "Northglenn", state_province: "Colorado", zip: "80234"},
  {site_name: "360 Roseland", address: "9230 S Lincoln Ave", city: "Roseland", state_province: "Nebraska", zip: "68973"},
  {site_name: "362 Norfork", address: "13862 Highway 5 S", city: "Norfork", state_province: "Arkansas", zip: "72658"},
  {site_name: "367 Arthur", address: "309 Fir St", city: "Arthur", state_province: "Nebraska", zip: "69121"},
  {site_name: "368 Harrisburg", address: "306 State St", city: "Harrisburg", state_province: "Nebraska", zip: "69345"},
  {site_name: "369 Purdum", address: "84451 Purdum Ave", city: "Purdum", state_province: "Nebraska", zip: "69157"},
  {site_name: "370 Dunning", address: "403 Jewett Ave", city: "Dunning", state_province: "Nebraska", zip: "68833"},
  {site_name: "371 Cedar Rapids", address: "214 W Main St", city: "Cedar Rapids", state_province: "Nebraska", zip: "68627"},
  {site_name: "373 Saint Edward", address: "207 Beaver St", city: "Saint Edward", state_province: "Nebraska", zip: "68660"},
  {site_name: "381 Midway", address: "323 Highway 178 W", city: "Midway", state_province: "Arkansas", zip: "72651"},
  {site_name: "382 Gentry", address: "899 W Main St", city: "Gentry", state_province: "Arkansas", zip: "72734"},
  {site_name: "383 Rogers", address: "4600 W Walnut St", city: "Rogers", state_province: "Arkansas", zip: "72756"},
  {site_name: "385 Bentonville", address: "1706 S Walton Blvd", city: "Bentonville", state_province: "Arkansas", zip: "72712"},
  {site_name: "386 Gravette", address: "613 Main St Sw", city: "Gravette", state_province: "Arkansas", zip: "72736"},
  {site_name: "387 Big Flat", address: "100 Community Dr", city: "Big Flat", state_province: "Arkansas", zip: "72617"},
  {site_name: "388 Decatur", address: "750 E Roller Ave", city: "Decatur", state_province: "Arkansas", zip: "72722"},
  {site_name: "391 Hamilton", address: "1706 Military Street South", city: "Hamilton", state_province: "Arkansas", zip: "72003"},
  {site_name: "393 Henderson", address: "13091 Highway 62 E", city: "Henderson", state_province: "Arkansas", zip: "72544"},
  {site_name: "397 Pea Ridge", address: "468 N Curtis Ave", city: "Pea Ridge", state_province: "Arkansas", zip: "72751"},
  {site_name: "401 Rogers", address: "401 N 8Th St", city: "Rogers", state_province: "Arkansas", zip: "72756"},
  {site_name: "406 Harrison", address: "215 W Industrial Park Rd", city: "Harrison", state_province: "Arkansas", zip: "72601"},
  {site_name: "409 Cave Springs", address: "115 E Midway St", city: "Cave Springs", state_province: "Arkansas", zip: "72718"},
  {site_name: "412 Gateway", address: "17260 Highway 37 N", city: "Gateway", state_province: "Arkansas", zip: "72733"},
  {site_name: "423 Adamsville", address: "2473 Hackworth Road", city: "Adamsville", state_province: "Arkansas", zip: "72026"},
  {site_name: "433 Bay Minette", address: "701 Mcmeans Ave", city: "Bay Minette", state_province: "Missouri", zip: "63540"},
  {site_name: "435 Golden City", address: "519 Main St", city: "Golden City", state_province: "Missouri", zip: "64748"},
  {site_name: "442 Mindenmines", address: "604 Main St", city: "Mindenmines", state_province: "Missouri", zip: "64769"},
  {site_name: "447 Lamar", address: "131 W 11Th St", city: "Lamar", state_province: "Missouri", zip: "64759"},
  {site_name: "453 Butler", address: "114 W Ohio St", city: "Butler", state_province: "Missouri", zip: "64730"},
  {site_name: "465 Sturgeon", address: "111 N Wentz St", city: "Sturgeon", state_province: "Missouri", zip: "65284"},
  {site_name: "466 Centralia", address: "104 W Sneed St", city: "Centralia", state_province: "Missouri", zip: "65240"},
  {site_name: "471 Columbia", address: "511 E Walnut St", city: "Columbia", state_province: "Missouri", zip: "65201"},
  {site_name: "473 Hume", address: "101 Main St", city: "Hume", state_province: "Missouri", zip: "64752"},
  {site_name: "476 Birmingham", address: "9248 Parkway East", city: "Birmingham", state_province: "Missouri", zip: "64427"},
  {site_name: "480 Ionia", address: "206 N Main St", city: "Ionia", state_province: "Missouri", zip: "65335"},
  {site_name: "487 Glenallen", address: "1 Short St", city: "Glenallen", state_province: "Missouri", zip: "63751"},
  {site_name: "4923 Commerce City", address: "7351 Magnolia St", city: "Commerce City", state_province: "Colorado", zip: "80022"},
  {site_name: "493 Brewton", address: "2041 Douglas Avenue", city: "Brewton", state_province: "Missouri", zip: "64449"},
  {site_name: "494 Moulton", address: "15445 Highway 24", city: "Moulton", state_province: "Missouri", zip: "65280"},
  {site_name: "497 Patton", address: "1000 State Route 51", city: "Patton", state_province: "Missouri", zip: "63662"},
  {site_name: "498 Calera", address: "5100 Hwy 31", city: "Calera", state_province: "Missouri", zip: "64480"},
  {site_name: "50 Andalusia", address: "540 West Bypass", city: "Andalusia", state_province: "Iowa", zip: "50858"},
  {site_name: "51 Griswold", address: "608 4Th St", city: "Griswold", state_province: "Iowa", zip: "51535"},
  {site_name: "514 Athens", address: "1011 US Hwy 72 East", city: "Athens", state_province: "Iowa", zip: "50859"},
  {site_name: "518 Massena", address: "99 Main St", city: "Massena", state_province: "Iowa", zip: "50853"},
  {site_name: "520 Atlantic", address: "1630 E 7Th St", city: "Atlantic", state_province: "Iowa", zip: "50022"},
  {site_name: "521 Attalla", address: "973 Gilbert Ferry Road Se", city: "Attalla", state_province: "Iowa", zip: "50841"},
  {site_name: "532 Wiota", address: "405 Pioneer Ave", city: "Wiota", state_province: "Iowa", zip: "50274"},
  {site_name: "535 Lowden", address: "308 Washington Ave", city: "Lowden", state_province: "Iowa", zip: "52255"},
  {site_name: "551 Ashland", address: "131 E Broadway", city: "Ashland", state_province: "Missouri", zip: "65010"},
  {site_name: "556 Saint Joseph", address: "3906 Oakland Ave", city: "Saint Joseph", state_province: "Missouri", zip: "64506"},
  {site_name: "560 Columbia", address: "3709 Sandman Ln", city: "Columbia", state_province: "Missouri", zip: "65201"},
  {site_name: "561 Gardendale", address: "890 Odum Road", city: "Gardendale", state_province: "Missouri", zip: "64421"},
  {site_name: "562 Columbia", address: "101 S Providence Rd", city: "Columbia", state_province: "Missouri", zip: "65203"},
  {site_name: "563 Jackson", address: "4206 N College Ave", city: "Jackson", state_province: "Missouri", zip: "64491"},
  {site_name: "567 Jacksonville", address: "1625 Pelham South", city: "Jacksonville", state_province: "Missouri", zip: "64482"},
  {site_name: "570 Hueytown", address: "1007 Red Farmer Drive", city: "Hueytown", state_province: "Iowa", zip: "52206"},
  {site_name: "571 Leeds", address: "8551 Whitfield Ave", city: "Leeds", state_province: "Missouri", zip: "64446"},
  {site_name: "578 Millbrook", address: "145 Kelley Blvd", city: "Millbrook", state_province: "Missouri", zip: "63352"},
  {site_name: "615 Stickney", address: "309 Main St", city: "Stickney", state_province: "South Dakota", zip: "57375"},
  {site_name: "631 Hitchcock", address: "386 Clarke St", city: "Hitchcock", state_province: "South Dakota", zip: "57348"},
  {site_name: "635 Wessington", address: "170 Wessington St S", city: "Wessington", state_province: "South Dakota", zip: "57381"},
  {site_name: "650 Thornton", address: "8804 Washington St", city: "Thornton", state_province: "Colorado", zip: "80229"},
  {site_name: "670 Alamosa", address: "505 3Rd St", city: "Alamosa", state_province: "Colorado", zip: "81101"},
  {site_name: "685 Centennial", address: "7255 S Havana St Ste 140", city: "Centennial", state_province: "Colorado", zip: "80112"},
  {site_name: "700 Montgomery", address: "6495 Atlanta Hwy", city: "Montgomery", state_province: "Missouri", zip: "65264"},
  {site_name: "76 Mason City", address: "2400 4Th St Sw", city: "Mason City", state_province: "Iowa", zip: "50401"},
  {site_name: "834 Burlington", address: "513 Main St", city: "Burlington", state_province: "Oklahoma", zip: "73722"},
  {site_name: "838 Oxford", address: "92 Plaza Lane", city: "Oxford", state_province: "Oklahoma", zip: "74965"},
  {site_name: "846 Ozark", address: "1537 Hwy 231 South", city: "Ozark", state_province: "Oklahoma", zip: "74931"},
  {site_name: "858 Watonga", address: "121 N Noble Ave", city: "Watonga", state_province: "Oklahoma", zip: "73772"},
  {site_name: "860 Cherokee", address: "1780 S Grand Ave", city: "Cherokee", state_province: "Oklahoma", zip: "73728"},
  {site_name: "863 Atoka", address: "409 E Court St", city: "Atoka", state_province: "Oklahoma", zip: "74525"},
  {site_name: "865 Lane", address: "11820 E Highway 3", city: "Lane", state_province: "Oklahoma", zip: "74555"},
  {site_name: "867 Caney", address: "200 W Main St", city: "Caney", state_province: "Oklahoma", zip: "74533"},
  {site_name: "873 Turpin", address: "419 S Main St", city: "Turpin", state_province: "Oklahoma", zip: "73950"},
  {site_name: "876 Bokchito", address: "118 W Main St", city: "Bokchito", state_province: "Oklahoma", zip: "74726"},
  {site_name: "877 Kenefic", address: "117 Mary St", city: "Kenefic", state_province: "Oklahoma", zip: "74748"},
  {site_name: "878 Forgan", address: "115 S Broadway St", city: "Forgan", state_province: "Oklahoma", zip: "73938"},
  {site_name: "881 Erick", address: "119 W 3Rd St", city: "Erick", state_province: "Oklahoma", zip: "73645"},
  {site_name: "886 Geary", address: "120 Nw 1St St", city: "Geary", state_province: "Oklahoma", zip: "73040"},
  {site_name: "887 Greenfield", address: "100 Madison St", city: "Greenfield", state_province: "Oklahoma", zip: "73043"},
  {site_name: "890 Hitchcock", address: "107 W Main St", city: "Hitchcock", state_province: "Oklahoma", zip: "73744"},
  {site_name: "891 Canton", address: "202 W Main St", city: "Canton", state_province: "Oklahoma", zip: "73724"},
  {site_name: "905 Mobile", address: "685 Schillinger Rd", city: "Mobile", state_province: "Colorado", zip: "80221"},
  {site_name: "906 Aurora", address: "18555 E Smoky Hill Rd", city: "Aurora", state_province: "Colorado", zip: "80015"},
  {site_name: "914 Centennial", address: "2221 E Arapahoe Rd", city: "Centennial", state_province: "Colorado", zip: "80122"},
  {site_name: "921 Greenwood Vlg", address: "8525 E Arapahoe Rd", city: "Greenwood Vlg", state_province: "Colorado", zip: "80112"},
  {site_name: "927 Littleton", address: "1500 W Littleton Blvd Ste 110-E", city: "Littleton", state_province: "Colorado", zip: "80120"},
  {site_name: "933 Las Animas", address: "513 6Th St", city: "Las Animas", state_province: "Colorado", zip: "81054"},
  {site_name: "95 Spencer", address: "11 E 18Th St", city: "Spencer", state_province: "Iowa", zip: "51301"},
  {site_name: "953 Laramie", address: "152 N 5Th St", city: "Laramie", state_province: "Wyoming", zip: "82072"},
  {site_name: "954 Lovell", address: "167 E 3Rd St", city: "Lovell", state_province: "Wyoming", zip: "82431"},
  {site_name: "961 Burlington", address: "211 S Main St", city: "Burlington", state_province: "Wyoming", zip: "82411"},
  {site_name: "966 Cowley", address: "71 E Main St", city: "Cowley", state_province: "Wyoming", zip: "82420"},
  {site_name: "979 Gillette", address: "2005 S Douglas Hwy", city: "Gillette", state_province: "Wyoming", zip: "82718"},
  {site_name: "981 Fort Cobb", address: "408 N Hazlett St", city: "Fort Cobb", state_province: "Oklahoma", zip: "73038"},
  {site_name: "986 Apache", address: "302 E Evans Ave", city: "Apache", state_province: "Oklahoma", zip: "73006"},
];
